config/routes.rb
Rails.application.routes.draw do
  resources :orders
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  # get 'order_records', to: "orders#order_records"
  controller :home do
    get :convert
    get :pdf
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def pdf
    # this method will be called by Dhalang
  end

  def convert
    _url = request.base_url + pdf_path
    _pdf = Dhalang::PDF.get_from_url(_url)
    _file_name = "Report" 
        File.open("#{Rails.root}/public/#{_file_name}.pdf", "w+b") << _pdf
  redirect_to "/#{_file_name}.pdf"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  # def index
  #   @orders = Order.all
  #   respond_to do |format|
  #     format.html
  #     format.pdf do
  #       render template: "orders/index.html.erb",
  #         pdf: "Orders: #{@orders.count}"
  #     end
  #   end
  # end

  def index
    @orders = Order.all
    # respond_to do |format|
    #   format.html
    #   format.pdf do
    #     render pdf: "orders/index.html.erb",
    #      window_status: "FLAG_FOR_PDF"
    #   end
    # end


    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "orders/index.html.erb",
               layout: "pdf",
               window_status: "FLAG_FOR_PDF" # Wait until window.status is equal to this string before rendering page
      end
    end
  #   binary_pdf = Dhalang::PDF.get_from_url("https://www.google.com") 
  #   send_data(binary_pdf, filename: 'orders/index.html.erb.pdf', type: 'application/pdf') 
  end


# def example_controller_method
#   binary_pdf = Dhalang::PDF.get_from_url("https://www.google.com")  
#   send_data(binary_pdf, filename: 'pdfofgoogle.pdf', type: 'application/pdf')  
# end




















  # render pdf: "orders",
  # page_size: "A4",
  # template: "orders/order.pdf.erb",
  # javascript_delay: 10000
  # # disable_javascript :false 
          

  # GET /orders/1 or /orders/1.json
  def show
  end



  def completed_tasks
    render json: Task.group(:goal_id).group_by_day(:completed_at).count.chart_json
  end


  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:price, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/home/index.html.erb
<div class="" style="padding: 30px; margin: auto; text-align: center;">
	<%= link_to "CONVERT TO PDF", convert_path, target: "_blank" %>
</div>
<canvas id="sample"></canvas>
<script type="text/javascript">
	<%= render "home/partials/main.js"%>
</script>

app/views/home/partials/_main.js.erb
var MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
var config = {
	type: 'line',
	data: {
		labels: ['January', 'February', 'March', 'April', 'May', 'June', 'July'],
		datasets: [{
			label: 'My First dataset',
			borderColor: "#C6C22F",
			backgroundColor: "#C6C22F",
			data: [
				44,
				55,
				20,
				21,
				89,
				52,
				33
			],
		}, {
			label: 'My Second dataset',
			borderColor: "#4DAA33",
			backgroundColor: "#4DAA33",
			data: [
				24,
				55,
				60,
				11,
				89,
				82,
				73
			],
		}, {
			label: 'My Third dataset',
			borderColor: "#C559A5",
			backgroundColor: "#C559A5",
			data: [
				41,
				55,
				94,
				61,
				81,
				52,
				30
			],
		}, {
			label: 'My Third dataset',
			borderColor: "#45CCB7",
			backgroundColor: "#45CCB7",
			data: [
				23,77,58,43,45,75,32
			],
		}]
	},
	options: {
		responsive: true,
		title: {
			display: true,
			text: 'Chart.js Line Chart - Stacked Area'
		},
		tooltips: {
			mode: 'index',
		},
		hover: {
			mode: 'index'
		},
		scales: {
			xAxes: [{
				scaleLabel: {
					display: true,
					labelString: 'Month'
				}
			}],
			yAxes: [{
				stacked: true,
				scaleLabel: {
					display: true,
					labelString: 'Value'
				}
			}]
		}
	}
};

window.onload = function() {
	var ctx = document.getElementById('sample').getContext('2d');
	window.myLine = new Chart(ctx, config);
};

app/views/home/pdf.html.erb
<canvas id="sample"></canvas>

<script type="text/javascript">
	<%= render "home/partials/main.js"%>
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chartwicked</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <a href="/users/sign_out"><span>SignOut</span></a>
    <% else %>
      <a href="/users/sign_up"><span>SignUp</span></a>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/> 
    <%#= stylesheet_link_tag wicked_pdf_asset_base64("pdf") %>
    <%#= javascript_include_tag wicked_pdf_asset_base64("number_pages") %>
  </head>
  <body onload="number_pages">
    <div id="header">
    </div>
    <div id="content">
      <%= yield%>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<%= wicked_pdf_javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<%= wicked_pdf_javascript_include_tag "https://code.jquery.com/jquery-3.2.1.min.js" %>
<%= wicked_pdf_javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/chartkick/2.2.4/chartkick.min.js" %>

<%= javascript_include_tag "http://code.jquery.com/jquery-1.10.0.min.js" %>
<%= javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.min.js" %>
<%= javascript_include_tag "https://www.google.com/jsapi" %>
<%= wicked_pdf_javascript_include_tag "chartkick" %> 

Dhalang::PDF.get_from_html("<html><head></head><body><h1>examplestring</h1></body></html>") 

<!-- , {margin: { top: 100, right: 100, bottom: 100, left: 100}}
 -->

<p id="notice"><%= notice %></p>
<button id="alert">Click</button>
<h1>Orders</h1>
      <%= pie_chart Order.group(:status).count %>
      <%= line_chart Order.group(:status).count %>
      <%= link_to "PDF", orders_path(format: :pdf) %>
<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.price %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  
<%= link_to 'New Order', new_order_path %>

<script type="text/javascript">
    setTimeout((function () {
        window.status = "FLAG_FOR_PDF";
        console.log("FLAG_FOR_PDF");
        Object.keys(Chartkick.charts).forEach(function (key) {
            Chartkick.charts[key].redraw();
        });
    }), 3000);

    $("#alert").click(function(){
      alert("The paragraph was clicked.");
    });
</script>

app/views/orders/index1.html.erb
<%= wicked_pdf_javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<%= wicked_pdf_javascript_include_tag "https://code.jquery.com/jquery-3.2.1.min.js" %>
<%= wicked_pdf_javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/chartkick/2.2.4/chartkick.min.js" %>

<%= javascript_include_tag "http://code.jquery.com/jquery-1.10.0.min.js" %>
<%= javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.min.js" %>
<%= javascript_include_tag "https://www.google.com/jsapi" %>
<%= wicked_pdf_javascript_include_tag "chartkick" %> 






   
<p id="notice"><%= notice %></p>
<button id="alert">Click</button>
<h1>Orders</h1>
      <%= pie_chart Order.group(:status).count %>
      <%= line_chart Order.group(:status).count %>
      <%= link_to "PDF", orders_path(format: :pdf) %>
<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.price %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
  
<%= link_to 'New Order', new_order_path %>

<script type="text/javascript">
    setTimeout((function () {
        window.status = "FLAG_FOR_PDF";
        console.log("FLAG_FOR_PDF");
        Object.keys(Chartkick.charts).forEach(function (key) {
            Chartkick.charts[key].redraw();
        });
    }), 3000);

    $("#alert").click(function(){
      alert("The paragraph was clicked.");
    });
</script>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/order_records.html.erb
<%= pie_chart Order.group(:status).count %>

<%= wicked_pdf_javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<%= wicked_pdf_javascript_include_tag "https://code.jquery.com/jquery-3.2.1.min.js" %>
<%= wicked_pdf_javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/chartkick/2.2.4/chartkick.min.js" %>
<%= javascript_include_tag "http://code.jquery.com/jquery-1.10.0.min.js" %>
<%= javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.min.js" %>  
    


<b>Date of extract: </b>
<%= Date.today %>
<br><br>

<b>Orders count:</b>
<%= @orders.count %>
<br><br>  

<table style="width:100%">
  <thead>
    <tr>
      <th>id</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <%= content_tag :tr, id: dom_id(order), class: dom_class(order) do %>
        <td style="padding-left: 100px,column-width: 50px;"><%= order.id %></td>
        <td style="padding-left: 30px "><%= order.price %></td>
        <td style="padding-left: 30px column-width: 50px;"><%= order.status %></td>
      <% end %>
    <% end %>
  </tbody>
</table> 

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>